### ISSUE TITLE
User generation and download of VPN certificates

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/registration-app#52]

**Comment by rbclark** [comment]
Considerations: If we are doing this in Dokku then every time we deploy we will have the overhead of installing this software as well. Dokku does support volumes so it may make sense to create a volume for the VPN master certificate and another volume that is shared between the VPN generation container and the Dokku version of the scoreboard.

**Comment by rbclark** [comment]
More considerations, we actually have to have this completed before the competition and I'm very against trying to migrate to Dokku right now, especially considering everything is working so well in Heroku. Need to setup S3 to handle this syncing. Also need to have this done before the competition since we actually need this functionality for the competition.
